import { NextResponse } from 'next/server';
import { z } from 'zod';

const querySchema = z.object({
  cursor: z.coerce.number().min(0).default(0)
});

const PAGE_SIZE = 30;
const TOTAL = 180;

export async function GET(request) {
  const parsed = querySchema.safeParse({
    cursor: request.nextUrl.searchParams.get('cursor') ?? 0
  });

  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }

  const { cursor } = parsed.data;

  const items = Array.from({ length: PAGE_SIZE }, (_, index) => {
    const id = cursor + index + 1;
    return {
      id,
      title: `Feed item ${id}`,
      body: `This row is generated by a route handler for data-lab demos.`
    };
  }).filter((item) => item.id <= TOTAL);

  const nextCursor = cursor + PAGE_SIZE < TOTAL ? cursor + PAGE_SIZE : undefined;

  return NextResponse.json({
    items,
    nextCursor
  });
}
